In [13]:
import pandas as pd
import numpy as np
import seaborn as sns

In [14]:
df = pd.read_csv('emails.csv')

In [15]:
df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [16]:
df.['spam'].value_counts()

SyntaxError: invalid syntax (Temp/ipykernel_7888/3606966225.py, line 1)

In [17]:
df.drop_duplicates(inplace=True)

In [18]:
df.isnull().sum()

text    0
spam    0
dtype: int64

# Separate X and Y

In [19]:
x = df.text.values

In [20]:
y=df.spam.values

In [21]:
x

array(["Subject: naturally irresistible your corporate identity  lt is really hard to recollect a company : the  market is full of suqgestions and the information isoverwhelminq ; but a good  catchy logo , stylish statlonery and outstanding website  will make the task much easier .  we do not promise that havinq ordered a iogo your  company will automaticaily become a world ieader : it isguite ciear that  without good products , effective business organization and practicable aim it  will be hotat nowadays market ; but we do promise that your marketing efforts  will become much more effective . here is the list of clear  benefits : creativeness : hand - made , original logos , specially done  to reflect your distinctive company image . convenience : logo and stationery  are provided in all formats ; easy - to - use content management system letsyou  change your website content and even its structure . promptness : you  will see logo drafts within three business days . affordability : y

# Split Dataset

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2)

# Data Preprocessing

In [42]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [43]:
cv = TfidfVectorizer()
x_train = cv.fit_transform(xtrain)

In [44]:
x_train.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.02262083, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

# ML Algorithm

In [45]:
from sklearn.naive_bayes import MultinomialNB

In [46]:
model = MultinomialNB()
model.fit(x_train,ytrain)

MultinomialNB()

In [47]:
x_test = cv.transform(xtest)

In [48]:
x_test.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.06260969, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.0573351 , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.11093256, 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [49]:
model.score(x_test,ytest)

0.884108867427568

In [39]:
emails = ['Hey, I am looking for ML in Bengali Language','Hey, you win a iphone 10 giveway for free. Please do the survey.']

In [40]:
cv_emails = cv.transform(emails)

In [41]:
model.predict(cv_emails)

array([0, 1], dtype=int64)

# Performance

In [35]:
pred = model.predict(x_test)

In [36]:
pred

array([0, 0, 1, ..., 1, 0, 1], dtype=int64)

In [38]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(ytest,pred)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(ytest,pred)

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(ytest,pred))